// This file is auto-generated by Supabase CLI
// To regenerate, run: npx supabase gen types typescript --project-id your-project-id > lib/supabase/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          legal_name: string | null
          address: string | null
          timezone: string
          currency: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          legal_name?: string | null
          address?: string | null
          timezone?: string
          currency?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          legal_name?: string | null
          address?: string | null
          timezone?: string
          currency?: string
          created_at?: string
          updated_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          organization_id: string
          first_name: string | null
          last_name: string | null
          email: string
          role: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          organization_id: string
          first_name?: string | null
          last_name?: string | null
          email: string
          role?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          first_name?: string | null
          last_name?: string | null
          email?: string
          role?: string
          created_at?: string
          updated_at?: string
        }
      }
      customers: {
        Row: {
          id: string
          organization_id: string
          name: string
          email: string
          company: string | null
          default_terms: string
          total_invoiced: number
          outstanding: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          name: string
          email: string
          company?: string | null
          default_terms?: string
          total_invoiced?: number
          outstanding?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          name?: string
          email?: string
          company?: string | null
          default_terms?: string
          total_invoiced?: number
          outstanding?: number
          created_at?: string
          updated_at?: string
        }
      }
      products: {
        Row: {
          id: string
          organization_id: string
          name: string
          description: string | null
          unit_price: number
          unit: string
          tax_category: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          name: string
          description?: string | null
          unit_price: number
          unit: string
          tax_category?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          name?: string
          description?: string | null
          unit_price?: number
          unit?: string
          tax_category?: string
          created_at?: string
          updated_at?: string
        }
      }
      invoices: {
        Row: {
          id: string
          organization_id: string
          customer_id: string
          number: string
          po_number: string | null
          status: string
          issue_date: string
          due_date: string
          paid_date: string | null
          currency: string
          subtotal: number
          tax_total: number
          discount_amount: number
          total: number
          notes: string | null
          terms: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          customer_id: string
          number: string
          po_number?: string | null
          status?: string
          issue_date: string
          due_date: string
          paid_date?: string | null
          currency?: string
          subtotal?: number
          tax_total?: number
          discount_amount?: number
          total?: number
          notes?: string | null
          terms?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          customer_id?: string
          number?: string
          po_number?: string | null
          status?: string
          issue_date?: string
          due_date?: string
          paid_date?: string | null
          currency?: string
          subtotal?: number
          tax_total?: number
          discount_amount?: number
          total?: number
          notes?: string | null
          terms?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      invoice_line_items: {
        Row: {
          id: string
          invoice_id: string
          product_id: string | null
          name: string
          description: string | null
          quantity: number
          unit_price: number
          tax_rate: number
          total: number
          created_at: string
        }
        Insert: {
          id?: string
          invoice_id: string
          product_id?: string | null
          name: string
          description?: string | null
          quantity: number
          unit_price: number
          tax_rate?: number
          total: number
          created_at?: string
        }
        Update: {
          id?: string
          invoice_id?: string
          product_id?: string | null
          name?: string
          description?: string | null
          quantity?: number
          unit_price?: number
          tax_rate?: number
          total?: number
          created_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          organization_id: string
          invoice_id: string
          amount: number
          method: string
          status: string
          transaction_id: string | null
          date: string
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          invoice_id: string
          amount: number
          method: string
          status?: string
          transaction_id?: string | null
          date?: string
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          invoice_id?: string
          amount?: number
          method?: string
          status?: string
          transaction_id?: string | null
          date?: string
          created_at?: string
        }
      }
      audit_events: {
        Row: {
          id: string
          organization_id: string
          user_id: string | null
          event: string
          entity: string
          entity_id: string
          details: string
          actor: string
          timestamp: string
        }
        Insert: {
          id?: string
          organization_id: string
          user_id?: string | null
          event: string
          entity: string
          entity_id: string
          details: string
          actor: string
          timestamp?: string
        }
        Update: {
          id?: string
          organization_id?: string
          user_id?: string | null
          event?: string
          entity?: string
          entity_id?: string
          details?: string
          actor?: string
          timestamp?: string
        }
      }
      reminder_rules: {
        Row: {
          id: string
          organization_id: string
          timing: string
          day_offset: number
          tone: string
          subject: string
          body: string
          enabled: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          timing: string
          day_offset: number
          tone: string
          subject: string
          body: string
          enabled?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          timing?: string
          day_offset?: number
          tone?: string
          subject?: string
          body?: string
          enabled?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      reminder_logs: {
        Row: {
          id: string
          organization_id: string
          invoice_id: string
          reminder_rule_id: string | null
          status: string
          date: string
        }
        Insert: {
          id?: string
          organization_id: string
          invoice_id: string
          reminder_rule_id?: string | null
          status: string
          date?: string
        }
        Update: {
          id?: string
          organization_id?: string
          invoice_id?: string
          reminder_rule_id?: string | null
          status?: string
          date?: string
        }
      }
      attachments: {
        Row: {
          id: string
          organization_id: string
          invoice_id: string | null
          file_name: string
          file_size: number
          file_type: string
          storage_path: string
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          invoice_id?: string | null
          file_name: string
          file_size: number
          file_type: string
          storage_path: string
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          invoice_id?: string | null
          file_name?: string
          file_size?: number
          file_type?: string
          storage_path?: string
          created_at?: string
        }
      }
      organization_settings: {
        Row: {
          organization_id: string
          logo_url: string | null
          accent_color: string
          invoice_template: string
          peppol_enabled: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          organization_id: string
          logo_url?: string | null
          accent_color?: string
          invoice_template?: string
          peppol_enabled?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          organization_id?: string
          logo_url?: string | null
          accent_color?: string
          invoice_template?: string
          peppol_enabled?: boolean
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      user_organization_id: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
